### ISSUE TITLE
Dados demográficos

### ISSUE THREAD

**Issue by santosbio** [DP6/gas#3]
Atualmente, o Google atualizou seu código para capturar e exibir dados demográficos sobre os usuários (idade, sexo, etc...). Há alguma maneira de habilitar essa função no GAS?

**Comment by andremafei** [comment]
Oficialmente ainda não. Mas você pode resolver isso seguindo os seguintes passos: 

1 - salve um cópia local do arquivo https://github.com/digitalinc/gas/blob/master/dist/gas-1.10.1.js 

2 - apague as linhas de 1751 à 1756

3 - cole no lugar das linhas apagadas essa linha:
ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';

4 - hospede esse .js modificado em seu site e mude a linha abaixo na tag do site para que aponte para seu novo arquivo modificado:
ga.src = '//cdnjs.cloudflare.com/ajax/libs/gas/1.10.1/gas.min.js';

Mais detalhes sobre o porque isso é necessário em:
https://support.google.com/analytics/answer/2444872?hl=en

**Comment by gabrielhpugliese** [comment]
Algum motivo de não deixar por padrão o dc.js?

**Comment by andremafei** [comment]
Tecnicamente não há motivo. Acho que foi questão de falta de tempo mesmo. Mas tem uma questão política: "... When you make this update to your tracking code, you also need to update your privacy policy." em:
https://support.google.com/analytics/answer/2444872?hl=en
